options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1. Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/nest-app:$SHORT_SHA",
        "."
      ]

  # 2. Push image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/nest-app:$SHORT_SHA"
      ]

  # 3. Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "nest-app",
        "--image",
        "asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/nest-app:$SHORT_SHA",
        "--region",
        "asia-south1",
        "--platform",
        "managed",
        "--allow-unauthenticated"
      ]

images:
  - "asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/nest-app:$SHORT_SHA"
